### ISSUE TITLE
Hey Lorentz 

### ISSUE THREAD

**Issue by Snowiiii** [BeastLe9enD/sanctuary-island#1]
Lorentz ich vermisse euch schon Länger, Kannst du villiecht bitte deinen Discord Schicken <3

**Comment by BeastLe9enD** [comment]
@Snowiiii 
1. Schreibt man meinen Namen ohne T
2. Mein Discord Tag ist BeastLe9enD#7698
3. Ist das irgendwie die falsche Location dafür
